### PR TITLE
Fix protocol multicodecs numbers

### LINKED ISSUE #49: Why is there a protocols.csv in this repo?
This file is never parsed, and it seems to be outdated compared to the one in https://github.com/multiformats/multiaddr/.

### PR DESCRIPTION
**Pull request by Stebalien**
1. Swap udt/utp.
2. Fix udp (17 is SHA1)
3. Change them to hex so it's easier to compare them with the official
   multicodec table.
4. Remove the local protocols.csv table.

Fixes #49
Fixes multiformats/multicodec#51

### CODE REVIEW

**Comment by Stebalien** [comment]
Summoning @vyzo, @lgierth

**Comment by vyzo** [comment]
looks good, want to add P_CIRCUIT as well?

**Comment by vyzo** [comment]
Oh wait, we decided we are not adding that here!

**Comment by vyzo** [comment]
LGTM

**Comment by Stebalien** [comment]
I've added a commit fixing QUIC as well. Depends on https://github.com/multiformats/multicodec/pull/57.

**Comment by lgierth** [comment]
Feel free to merge when https://github.com/multiformats/multicodec/pull/57 is in :+1:

**Pull request merged**
