### PR TITLE
Create Jenkinsfile

### PR DESCRIPTION
**Pull request by victorb**

### CODE REVIEW

**Comment by VictorBjelkholm** [comment]
Not entirely sure what this error means.

```
/var/jenkins/workspace/iformats_go-multiaddr_PR-65-SZZROFF3E5TX3EGQHQQIMKREFGRX6QLD7MPVOTLACFIVVJDPJBSQ/src/github.com/ipfs/go-ipfs-api/shell.go:20:2: no Go files in /var/jenkins/workspace/iformats_go-multiaddr_PR-65-SZZROFF3E5TX3EGQHQQIMKREFGRX6QLD7MPVOTLACFIVVJDPJBSQ/src/github.com/multiformats/go-multiaddr
```

go-multiaddr has go-files (and tests), and not sure how go-ipfs-api is in the picture here?

**Comment by Stebalien** [comment]
I'm guessing that was a build error when building gx.

**Comment by VictorBjelkholm** [comment]
Ah, seems to be true. Ref for avoiding this (gx build failures/timeouts) in the future: https://github.com/ipfs/jenkins-libs/issues/6

**Comment by VictorBjelkholm** [comment]
This seems to consistently not work, so doesn't seem to be a temporary issue with building gx. Also, I'm not sure why this repository works differently? It's downloading the same version of gx as the rest of the golang repositories.

**Pull request closed without merging**
