### PR TITLE
Add HasPrefix() utility function

### PR DESCRIPTION
**Pull request by lgierth**
I sketched this out last night, it seems useful on first sight, but I don't have the time to work it out properly. Consider it up for grabs :)

### CODE REVIEW

**Comment by Stebalien** [comment]
Does `bytes.IsPrefix(a.Bytes(), b.Bytes())` not work?

**Comment by lgierth** [comment]
This one here works on the protocol and value boundaries. But hrm yeah I suppose if we're dealing with a multiaddr created through the proper functions, `Bytes()` will be on the boundaries too :)

**Comment by Stebalien** [comment]
(although it might be reasonable to add a function/method)

**Comment by Stebalien** [comment]
(but I'd rather not leave a PR around for that, we can just put it in an issue)

**Pull request closed without merging**
