### PR TITLE
P_CIRCUIT: support p2p-circuit addresses

### PR DESCRIPTION
**Pull request by vyzo**

### CODE REVIEW

**Comment by Kubuxu** [comment]
We usually register new protocols externally, example: https://github.com/libp2p/go-ws-transport/blob/master/websocket.go#L39

It might make sense for circuit as it isn't just generic transport.

**Comment by Stebalien** [comment]
@Kubuxu, So no multiprotocol registration?

**Comment by vyzo** [comment]
It is kind of necessary to implement dialing from the libp2p-circuit transport.
See also: https://github.com/libp2p/go-addr-util/pull/4

**Comment by vyzo** [comment]
Also, here: https://github.com/libp2p/go-libp2p-circuit/pull/3 (the user)

**Comment by vyzo** [comment]
Just to clarify, the protocol needs to be registerd before it can be added to the list of transports in go-addr-util, otherwise we have an initialization failure.

**Comment by vyzo** [comment]
@Kubuxu 
Alternative is to modify the code in go-addr-util to allow registration of protocols post initialization, which would not require the change.
I can do that too if you think we should adhere to "external protocol registration" policy, but I think it makes sense to add it to the list as it is intended to be a transport.

**Comment by Kubuxu** [comment]
As you can see, the websocket protocol registers late (it is not in this list) but can be in the go-addr-util list.

**Comment by vyzo** [comment]
Upon further thought and discussion, it's more scalable to register the new protocols dynamically and extend go-addr-util to support dynamic registration of transports.

Closing.

**Pull request closed without merging**
