### PR TITLE
store Multiaddrs as strings and don't use interfaces

### PR DESCRIPTION
**Pull request by Stebalien**
1. This saves one level of indirection, one distinct allocation, and a few bytes.
2. This allows Multiaddrs to be used as map keys (we can use this to make our Peerstore more efficient).
3. Removing the interface allows us to serialize these without copying.

This commit isn't as efficient as it could be. We could improve it slightly by using unsafe casts to temporarily treat strings as bytes. However I'm not sure this will improve performance much and, in general, this change will lead to fewer allocations overall.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
@Stebalien why not keep the interface, and just do:
```go
type multiaddr string
```

That way we get all the same benefits, plus the ability to have nil multiaddrs (making the upgrade path easier)

**Comment by Stebalien** [comment]
Note: I'm pretty sure that'll still require an additional allocation/indirection but it should be fairly cheep.

**Comment by Kubuxu** [comment]
I think Go is smart enough and allocates the type header in the same call as the string.

**Comment by Kubuxu** [comment]
> From a bit of quick testing, it looks like this is correct.

correct as in "it adds allocation"?

**Comment by Stebalien** [comment]
Correct as in it adds a level of indirection. Go may do something sneaky with the allocation but I kind of doubt it. Go *could* do something to avoid an extra object to GC (e.g., have some concept of ownership) but the complexity probably isn't worth it.

**Pull request closed without merging**
