### PR TITLE
Fix tor onion string conversion

### PR DESCRIPTION
**Pull request by david415**
added code for onion multiaddr string conversion; added a unit test as well. please review.

### CODE REVIEW

**Comment by ianopolous** [comment]
See discussion on similar PR: https://github.com/jbenet/go-multiaddr/pull/21

**Comment by ianopolous** [comment]
Don't forget the protocols.csv :-) then we're equivalent.

**Comment by david415** [comment]
please see my comments in
https://github.com/multiformats/go-multiaddr/pull/21

- the onion multiaddr should contain both the onion address and the port number. This makes sense since both peices of addressing info are logically at the same transportation level UNLIKE a IP address and TCP port which are located at different layers of the network stack.

**Comment by david415** [comment]
then merge #21 and we're done with this conversation and we can gradually move on to discussing the more interesting parts of the Tor integration

**Comment by jbenet** [comment]
Thanks very much for this, and for hashing out this stuff. great to hear Tor's port is part of the same. I will merge #21

**Comment by jbenet** [comment]
This has been addressed in https://github.com/multiformats/go-multiaddr/pull/21 -- thank you very much for championing this, @david415 @ianopolous

**Pull request closed without merging**
