### PR TITLE
fix udt<->utp inconsistency in protocols.{go,csv}

### PR DESCRIPTION
**Pull request by keks**
`protocols.go` said
```
	Protocol{P_UTP, 0, "utp", CodeToVarint(P_UTP)},
	Protocol{P_UDT, 0, "udt", CodeToVarint(P_UDT)},
```
and `protocols.csv` said
```
301	0	udt
302	0	utp
```

### CODE REVIEW

**Comment by lgierth** [comment]
LGTM, fixing it in the csv is better than fixing it in the code, since these codes go into the binary representations of multiaddrs and we currently can't really change the codes there.

**Comment by keks** [comment]
yup, that's what I thought

**Comment by jbenet** [comment]
good call 👍

**Comment by lgierth** [comment]
I just noticed that it should have been the other way round: /udt = 301, /utp = 302 -- that's what both multiaddr/protocols.csv and js-multiaddr have.

**Pull request merged**
