### PR TITLE
feat: move filters into a sub-package

### PR DESCRIPTION
**Pull request by Stebalien**
These really don't belong in the root package.

### CODE REVIEW

**Comment by Stebalien** [comment]
I agree that single-type packages are suboptimal, but it _doesn't_ belong in the root package. A multiaddr _set_ might belong in the root package, but this filter type is highly specialized (special IPNet functions, filter actions, etc.). Remember, this package has implementations in _many_ languages and needs to present a cohesive minimal interface.

How about a compromise:

1. Move `go-multiaddr-net` into `go-multiaddr/net`.
2. Move this filter package into `go-multiaddr/net`.

**Comment by raulk** [comment]
@Stebalien Deal taken! That simplifies our codebase even further. Is this something you plan on tackling?

**Comment by Stebalien** [comment]
Yeah. It's been annoying me for a while... I wonder if I can fold go-multiaddr-dns into the deal.

**Comment by raulk** [comment]
@Stebalien Nowwwww we're talking :-)

**Comment by Stebalien** [comment]
Replaced with #127.

**Pull request closed without merging**
